# Generated by Django 2.0.2 on 2020-02-01 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleNum', models.IntegerField()),
                ('statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.TextField()),
                ('articleNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicApp.Articles')),
            ],
        ),
        migrations.AddField(
            model_name='articledescription',
            name='articleNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicApp.Articles'),
        ),
    ]
