# Generated by Django 2.0.2 on 2020-02-01 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('articleNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicApp.Articles')),
            ],
        ),
    ]
