# Generated by Django 2.0.2 on 2020-02-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0002_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledescription',
            name='articleNum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='articleNum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='references',
            name='articleNum',
            field=models.IntegerField(),
        ),
    ]
