# Generated by Django 2.0.2 on 2020-02-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0003_auto_20200206_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledescription',
            name='articleNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicApp.Articles'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='articleNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicApp.Articles'),
        ),
        migrations.AlterField(
            model_name='references',
            name='articleNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicApp.Articles'),
        ),
    ]
