# Generated by Django 2.0.2 on 2020-05-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0004_auto_20200206_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('statement', models.TextField()),
                ('desccription', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
    ]
